apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cuwmviq5y-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cuwmviq5y-java-springboot-gitops